name: blog-ci
on: [push]
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1
      - run: zola build
      - uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: HtmlBundle
          if-no-files-found: error
          path: |
            ./public
