name: blog-deploy-production

on:
  push:
    branches:
      - main

jobs:
  zola-lftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1
      - run: zola build
      - run: |
          sudo apt-get -y update && sudo apt-get -y install lftp
      - env:
          SSH_PASS: ${{ secrets.YALI_PASS }}
        run: |
          lftp -c "set sftp:auto-confirm yes ; open --user thejpster --password ${SSH_PASS} sftp://yali.mythic-beasts.com ; set net:timeout 10 ; mirror -R -v -c -e ./public /home/thejpster/www/preview.thejpster.org.uk ; bye"
